server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka


ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

logging:
  level:
    com.kutake.springcloud.feign.PaymentServer: debug

feign:
  hystrix:
    enabled: true
