server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.190.111:8848
    sentinel:
      transport:
        dashboard: http://192.168.190.111:8080
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-service: http://nacos-payment-provider
